# Generated by Django 6.1.1 on 2026-09-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('BARANGAY_CLEARANCE', 'Barangay Clearance'), ('VOTER_ID', "COMELEC Voter's ID"), ('CMU_ID', 'CMU Student / Faculty ID'), ('GOV_ID', 'Government Issued ID')], default='BARANGAY_CLEARANCE', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_url',
            field=models.CharField(blank=True, help_text='Barangay clearance, Voter ID, or CMU ID proof', max_length=500, null=True),
        ),
    ]
