# Generated by Django 6.1.1 on 2026-09-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('municipality_city', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
                ('region', models.CharField(default='National Capital Region', max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('zones', models.JSONField(blank=True, default=list, help_text='List of zones/puroks within this barangay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barangay',
                'verbose_name_plural': 'Barangays',
                'db_table': 'barangays',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='barangays_code_25c5ec_idx'), models.Index(fields=['status'], name='barangays_status_a36933_idx')],
            },
        ),
    ]
