# Generated by Django 6.1 on 2026-09-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='municipality_city',
            field=models.CharField(default='Maramag', max_length=150),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='province',
            field=models.CharField(default='Bukidnon', max_length=150),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='region',
            field=models.CharField(default='Region X - Northern Mindanao', max_length=100),
        ),
    ]
