# Generated by Django 6.1.1 on 2026-09-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('ACCOUNT_VERIFIED', 'Account Verified'), ('REQUEST_CREATED', 'Request Created'), ('INVITATION_RECEIVED', 'Invitation Received'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('REQUEST_DECLINED', 'Request Declined'), ('ASSISTANCE_STARTED', 'Assistance Started'), ('ASSISTANCE_COMPLETED', 'Assistance Completed'), ('RATING_RECEIVED', 'Rating Received'), ('REPORT_STATUS_UPDATED', 'Report Status Updated'), ('ANNOUNCEMENT', 'Barangay Announcement'), ('RESOURCE_BORROWED', 'Resource Borrowed'), ('GENERAL', 'General Notice')], default='GENERAL', max_length=30)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.barangay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
