# Generated by Django 6.1.1 on 2026-09-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='HeartHandshake', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(blank=True, help_text='Null represents global/default categories accessible across barangays', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.barangay')),
            ],
            options={
                'verbose_name_plural': 'Assistance Categories',
                'db_table': 'assistance_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(blank=True, help_text='Null represents global/default skills', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='tenants.barangay')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.assistancecategory')),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_available', models.BooleanField(default=True)),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning (8:00 AM - 12:00 PM)'), ('AFTERNOON', 'Afternoon (1:00 PM - 5:00 PM)'), ('EVENING', 'Evening (5:00 PM - 8:00 PM)'), ('ALL_DAY', 'All Day (Flexible)')], default='ALL_DAY', max_length=20)),
                ('custom_start_time', models.TimeField(blank=True, null=True)),
                ('custom_end_time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_availabilities',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_skills',
            },
        ),
        migrations.AddIndex(
            model_name='assistancecategory',
            index=models.Index(fields=['barangay', 'is_active'], name='assistance__baranga_af1fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['barangay', 'is_active'], name='skills_baranga_572ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='skills_categor_0124d8_idx'),
        ),
        migrations.AddIndex(
            model_name='useravailability',
            index=models.Index(fields=['user', 'day_of_week'], name='user_availa_user_id_001649_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useravailability',
            unique_together={('user', 'day_of_week', 'time_slot')},
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user', 'skill'], name='user_skills_user_id_ee319c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
    ]
