# Generated by Django 6.1.1 on 2026-09-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(default='Flexible', max_length=100)),
                ('zone', models.CharField(help_text='Zone or Purok', max_length=100)),
                ('urgency', models.CharField(choices=[('LOW', 'Low Urgency'), ('MEDIUM', 'Medium Urgency'), ('HIGH', 'High Urgency'), ('EMERGENCY', 'Urgent / Priority')], default='MEDIUM', max_length=20)),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('attachment_url', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helping_requests', to=settings.AUTH_USER_MODEL)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to='tenants.barangay')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='skills.assistancecategory')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to=settings.AUTH_USER_MODEL)),
                ('required_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='skills.skill')),
            ],
            options={
                'db_table': 'assistance_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistanceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='INVITED', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('decline_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='assistance.assistancerequest')),
            ],
            options={
                'db_table': 'assistance_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.barangay')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_helper_transactions', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='assistance.assistancerequest')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_requester_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistance_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['barangay', 'status'], name='assistance__baranga_d32a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['requester', 'status'], name='assistance__request_9b0675_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['assigned_helper'], name='assistance__assigne_6c75e9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['category'], name='assistance__categor_2a6ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['required_skill'], name='assistance__require_a8d7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['preferred_date'], name='assistance__preferr_9d654f_idx'),
        ),
        migrations.AddIndex(
            model_name='assistanceinvitation',
            index=models.Index(fields=['helper', 'status'], name='assistance__helper__09534e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistanceinvitation',
            index=models.Index(fields=['request', 'status'], name='assistance__request_b49231_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assistanceinvitation',
            unique_together={('request', 'helper')},
        ),
        migrations.AddIndex(
            model_name='assistancetransaction',
            index=models.Index(fields=['barangay'], name='assistance__baranga_cde00e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancetransaction',
            index=models.Index(fields=['requester'], name='assistance__request_36d722_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancetransaction',
            index=models.Index(fields=['helper'], name='assistance__helper__55ee2f_idx'),
        ),
    ]
