# Generated by Django 6.1.1 on 2026-09-06 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_assistancerequest_completion_notes_and_more'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='helpers_needed',
            field=models.PositiveIntegerField(default=1, help_text='Number of volunteers needed'),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='linked_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_requests', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='reschedule_proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='reschedule_proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='reschedule_proposed_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='reschedule_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE', 'Helper En Route'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
