# Generated by Django 6.1.1 on 2026-09-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('skill_score', models.PositiveIntegerField(default=0)),
                ('barangay_score', models.PositiveIntegerField(default=0)),
                ('zone_score', models.PositiveIntegerField(default=0)),
                ('availability_score', models.PositiveIntegerField(default=0)),
                ('rating_score', models.PositiveIntegerField(default=0)),
                ('reasons', models.JSONField(default=list, help_text='Explanation badges why helper was matched')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_requests', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='assistance.assistancerequest')),
            ],
            options={
                'db_table': 'request_matches',
                'ordering': ['-total_score', '-calculated_at'],
                'indexes': [models.Index(fields=['request', '-total_score'], name='request_mat_request_954679_idx'), models.Index(fields=['helper'], name='request_mat_helper__522c9b_idx')],
                'unique_together': {('request', 'helper')},
            },
        ),
    ]
