# Generated by Django 6.1.1 on 2026-09-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal Notice'), ('IMPORTANT', 'Important Notice'), ('EMERGENCY', 'Emergency Advisory')], default='NORMAL', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_announcements', to=settings.AUTH_USER_MODEL)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tenants.barangay')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['barangay', 'is_active'], name='announcemen_baranga_0e5f70_idx'), models.Index(fields=['priority'], name='announcemen_priorit_370592_idx')],
            },
        ),
    ]
