# Generated by Django 6.1.1 on 2026-09-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('tenants', '0002_alter_barangay_municipality_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='alert_level',
            field=models.CharField(choices=[('ADVISORY', 'Advisory'), ('WATCH', 'Watch / Alert'), ('WARNING', 'Warning / Red Alert')], default='ADVISORY', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_emergency_broadcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tenants.barangay'),
        ),
    ]
