# Generated by Django 6.1.1 on 2026-09-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('TOOLS', 'Tools & Hardware'), ('GARDENING', 'Gardening & Outdoor'), ('ELECTRONICS', 'Electronics & Appliances'), ('EVENT_EQUIPMENT', 'Event & Party Equipment'), ('HOME_CARE', 'Home & Cleaning Care'), ('OTHER', 'Other Resource')], default='TOOLS', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair')], default='GOOD', max_length=20)),
                ('zone', models.CharField(help_text='Zone where item is located', max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REQUESTED', 'Requested'), ('BORROWED', 'Currently Borrowed'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tenants.barangay')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='resources.resource')),
            ],
            options={
                'db_table': 'resource_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['barangay', 'status'], name='resources_baranga_9d6e04_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['owner'], name='resources_owner_i_aff52f_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['resource', 'status'], name='resource_re_resourc_b5e4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['borrower'], name='resource_re_borrowe_0cc8e3_idx'),
        ),
    ]
