# Generated by Django 6.1.1 on 2026-09-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('ACCOUNT_VERIFICATION', 'Account Verification'), ('ACCOUNT_SUSPENSION', 'Account Suspension'), ('REQUEST_CREATION', 'Request Creation'), ('REQUEST_ACCEPTANCE', 'Request Acceptance'), ('REQUEST_CANCELLATION', 'Request Cancellation'), ('REQUEST_COMPLETION', 'Request Completion'), ('RATING_SUBMISSION', 'Rating Submission'), ('REPORT_CREATION', 'Report Creation'), ('REPORT_RESOLUTION', 'Report Resolution'), ('ANNOUNCEMENT_POSTED', 'Announcement Posted'), ('ADMIN_ACTION', 'Administrative Action')], max_length=40)),
                ('description', models.TextField()),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tenants.barangay')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['barangay', '-created_at'], name='activity_lo_baranga_026df8_idx'), models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx'), models.Index(fields=['action'], name='activity_lo_action_b49f28_idx')],
            },
        ),
    ]
